"""PDF export service for VisionIQ extraction results."""

from __future__ import annotations

from html import escape
from pathlib import Path
from typing import Mapping, Sequence

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer

from src.config import APP_NAME


def _paragraph_text(text: str) -> str:
    """Escape text and preserve line breaks for ReportLab paragraphs."""

    return escape(text or "").replace("\n", "<br/>")


def _build_styles(theme: str) -> dict[str, ParagraphStyle]:
    """Return ReportLab paragraph styles for the selected export theme."""

    base_styles = getSampleStyleSheet()
    dark_theme = (theme or "").strip().lower() == "dark"
    # Keep body text dark because the current export uses standard white PDF
    # pages. The theme changes accent and metadata treatment without reducing
    # readability for printing or sharing.
    body_color = colors.HexColor("#213040")
    muted_color = colors.HexColor("#4f6278") if dark_theme else colors.HexColor("#66758a")
    accent_color = colors.HexColor("#7fc7b8") if dark_theme else colors.HexColor("#315b8f")

    return {
        "title": ParagraphStyle(
            "VisionIQTitle",
            parent=base_styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=20,
            leading=25,
            textColor=accent_color,
            spaceAfter=12,
        ),
        "meta": ParagraphStyle(
            "VisionIQMeta",
            parent=base_styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=muted_color,
            spaceAfter=8,
        ),
        "body": ParagraphStyle(
            "VisionIQBody",
            parent=base_styles["BodyText"],
            fontName="Helvetica",
            fontSize=10.5,
            leading=15,
            textColor=body_color,
            spaceAfter=10,
        ),
        "heading": ParagraphStyle(
            "VisionIQHeading",
            parent=base_styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            textColor=accent_color,
            spaceBefore=10,
            spaceAfter=8,
        ),
    }


def create_extraction_pdf(
    *,
    results: Sequence[Mapping[str, object]],
    output_path: str | Path,
    title: str,
    theme: str = "Light",
) -> str:
    """Create a PDF from reviewed extraction results and return its path."""

    final_path = str(output_path)
    styles = _build_styles(theme)
    doc = SimpleDocTemplate(
        final_path,
        pagesize=A4,
        rightMargin=0.65 * inch,
        leftMargin=0.65 * inch,
        topMargin=0.6 * inch,
        bottomMargin=0.6 * inch,
        title=title or APP_NAME,
        author=APP_NAME,
    )

    story = [
        Paragraph(_paragraph_text(title or "VisionIQ Extracted Questions"), styles["title"]),
        Paragraph(f"Generated by {APP_NAME}. Review all extracted text before use.", styles["meta"]),
        Spacer(1, 0.1 * inch),
    ]

    for index, result in enumerate(results, start=1):
        file_name = str(result.get("file_name", f"Image {index}"))
        output = str(result.get("output", "")).strip() or "No extracted text available."

        story.append(Paragraph(f"Image {index}: {_paragraph_text(file_name)}", styles["heading"]))
        story.append(Paragraph(_paragraph_text(output), styles["body"]))

        if index < len(results):
            story.append(PageBreak())

    doc.build(story)
    return final_path
